apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-python-demo--reflect
  labels:
    app: knative-python-demo--reflect
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "50"
    spec:
      containerConcurrency: 1
      containers:
        - name: generator
          image: ghcr.io/brianlechthaler/knative-python-demo/reflect:main
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2
              memory: 2Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - LAS1